### ISSUE TITLE
Valid supported repo?

### ISSUE THREAD

**Issue by aure** [AudioKit/JUCE-AKSampler#1]
@getdunne This repo is getting pretty old, do you still feel like supporting it? I do not. Do you want me to transfer the repo to the getdunne github account or just delete it?

**Comment by getdunne** [comment]
Transfer this one to me please.

-shane
________________________________
From: Aurelius Prochazka ***@***.***>
Sent: Thursday, August 25, 2022 8:25:56 PM
To: AudioKit/JUCE-AKSampler ***@***.***>
Cc: Shane Dunne ***@***.***>; Mention ***@***.***>
Subject: [AudioKit/JUCE-AKSampler] Valid supported repo? (Issue #1)


@getdunne<https://github.com/getdunne> This repo is getting pretty old, do you still feel like supporting it? I do not. Do you want me to transfer the repo to the getdunne github account or just delete it?

**Comment by aure** [comment]
Looks like one can't transfer the ownership to anyone but themselves, so I think you can request the transfer and I may have to approve it.

**Comment by aure** [comment]
ping @getdunne Did you attempt the transfer?

**Comment by getdunne** [comment]
@aure I got it, thanks for the reminder.
